[package]
name = "cryptopals"
version = "0.1.0"
authors = ["dminor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.5.0"
rayon = "1.3.1"
